-- 1. Custom Types
CREATE TYPE public.user_role AS ENUM ('admin', 'teacher');
CREATE TYPE public.department_type AS ENUM ('유아부', '유치부', '어린이부', '청소년부', '청년부');
CREATE TYPE public.gender_type AS ENUM ('male', 'female');
CREATE TYPE public.transaction_type AS ENUM ('grant', 'deduct');
CREATE TYPE public.event_type AS ENUM ('special', 'meeting', 'worship');
CREATE TYPE public.budget_type AS ENUM ('income', 'expense');
CREATE TYPE public.item_status AS ENUM ('good', 'missing', 'repair');

-- 2. Profiles Table
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    role user_role DEFAULT 'teacher',
    department department_type,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Students Table
CREATE TABLE public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    gender gender_type NOT NULL,
    department department_type NOT NULL,
    birth_date DATE,
    school VARCHAR(100),
    grade VARCHAR(20),
    parent_name VARCHAR(50),
    parent_contact VARCHAR(20),
    total_talents INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Attendance Table
CREATE TABLE public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    attendance_date DATE NOT NULL,
    is_present BOOLEAN DEFAULT true,
    recorded_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(student_id, attendance_date)
);

-- 5. Talent Transactions Table
CREATE TABLE public.talent_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    type transaction_type NOT NULL,
    amount INTEGER NOT NULL CHECK (amount > 0),
    reason VARCHAR(255) NOT NULL,
    recorded_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Events Table
CREATE TABLE public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    location VARCHAR(100),
    type event_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Budget Transactions Table
CREATE TABLE public.budget_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE NOT NULL,
    type budget_type NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL CHECK (amount > 0),
    department department_type NOT NULL,
    recorded_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Items Table
CREATE TABLE public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    quantity INTEGER DEFAULT 1,
    location VARCHAR(100),
    status item_status DEFAULT 'good',
    department department_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Trigger for Updating Student's Total Talents
CREATE OR REPLACE FUNCTION update_student_total_talents()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        IF NEW.type = 'grant' THEN
            UPDATE public.students SET total_talents = total_talents + NEW.amount WHERE id = NEW.student_id;
        ELSIF NEW.type = 'deduct' THEN
            UPDATE public.students SET total_talents = total_talents - NEW.amount WHERE id = NEW.student_id;
        END IF;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        IF OLD.type = 'grant' THEN
            UPDATE public.students SET total_talents = total_talents - OLD.amount WHERE id = OLD.student_id;
        ELSIF OLD.type = 'deduct' THEN
            UPDATE public.students SET total_talents = total_talents + OLD.amount WHERE id = OLD.student_id;
        END IF;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_talents_on_transaction
AFTER INSERT OR DELETE ON public.talent_transactions
FOR EACH ROW EXECUTE FUNCTION update_student_total_talents();

-- 10. Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.talent_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users full access for now (Basic RBAC to be enhanced later)
CREATE POLICY "Allow authenticated users full access to profiles" ON public.profiles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users full access to students" ON public.students FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users full access to attendance" ON public.attendance FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users full access to talent_transactions" ON public.talent_transactions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users full access to events" ON public.events FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users full access to budget_transactions" ON public.budget_transactions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated users full access to items" ON public.items FOR ALL TO authenticated USING (true) WITH CHECK (true);
